import React from "react";
import Head from "next/head";
import { env } from "@/env";
import { cn } from "@/lib/utils";
import Header from "@/components/base/header";
import { Toaster } from "@/components/ui/sonner"
import {Roboto} from "next/font/google";

export const projectFont = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "auto",
});

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title>{env.NEXT_PUBLIC_PROJECT_NAME}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={cn(
          "flex min-h-screen flex-col pb-10",
          projectFont.className,
        )}
      >
        <Header />

        <div className="flex flex-1">{children}</div>

        <Toaster />
      </main>
    </>
  );
}
